// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct FootballRenterProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for FootballRenterProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = FootballRenterProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        FootballRenterProxyMethods { wrapped_tx: tx }
    }
}

pub struct FootballRenterProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> FootballRenterProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<BigUint<Env::Api>>,
    >(
        self,
        min_deposit_init: Arg0,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&min_deposit_init)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> FootballRenterProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> FootballRenterProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn set_minimum_deposit<
        Arg0: ProxyArg<BigUint<Env::Api>>,
    >(
        self,
        amount: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setMinDeposit")
            .argument(&amount)
            .original_result()
    }

    pub fn create_football_slot<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<u64>,
    >(
        self,
        start_time: Arg0,
        end_time: Arg1,
    ) -> TxTypedCall<Env, From, To, (), Gas, u64> {
        self.wrapped_tx
            .raw_call("create_football_slot")
            .argument(&start_time)
            .argument(&end_time)
            .original_result()
    }

    pub fn participate_football_slot<
        Arg0: ProxyArg<u64>,
    >(
        self,
        slot_id: Arg0,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("participate_football_slot")
            .argument(&slot_id)
            .original_result()
    }

    pub fn cancel_football_slot<
        Arg0: ProxyArg<u64>,
    >(
        self,
        slot_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("cancel_football_slot")
            .argument(&slot_id)
            .original_result()
    }

    pub fn set_football_field_manager<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        new_manager: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setFootballFieldManager")
            .argument(&new_manager)
            .original_result()
    }

    pub fn pay_court<
        Arg0: ProxyArg<u64>,
    >(
        self,
        slot_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("payCourt")
            .argument(&slot_id)
            .original_result()
    }

    pub fn set_football_court_cost<
        Arg0: ProxyArg<BigUint<Env::Api>>,
    >(
        self,
        cost: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setFootballCourtCost")
            .argument(&cost)
            .original_result()
    }

    pub fn confirm_slot<
        Arg0: ProxyArg<u64>,
    >(
        self,
        slot_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("confirmSlot")
            .argument(&slot_id)
            .original_result()
    }

    pub fn get_slot_status<
        Arg0: ProxyArg<u64>,
    >(
        self,
        slot_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValue4<Slot<Env::Api>, ManagedVec<Env::Api, ManagedAddress<Env::Api>>, BigUint<Env::Api>, bool>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getSlotStatus")
            .argument(&slot_id)
            .original_result()
    }

    pub fn get_reserved_slot_details<
        Arg0: ProxyArg<u64>,
    >(
        self,
        slot_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValue6<u64, u64, ManagedAddress<Env::Api>, BigUint<Env::Api>, bool, ManagedAddress<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getReservedSlotDetails")
            .argument(&slot_id)
            .original_result()
    }
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, Debug)]
pub struct Slot<Api>
where
    Api: ManagedTypeApi,
{
    pub start: u64,
    pub end: u64,
    pub payer_address: ManagedAddress<Api>,
    pub amount: BigUint<Api>,
    pub confirmed: bool,
    pub initiator_address: ManagedAddress<Api>,
}
