// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    football_renter
    (
        init => init
        upgrade => upgrade
        setMinDeposit => set_minimum_deposit
        create_football_slot => create_football_slot
        participate_football_slot => participate_football_slot
        cancel_football_slot => cancel_football_slot
        setFootballFieldManager => set_football_field_manager
        getReservedSlot => get_reserved_slot
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
